/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_oa_curvature_bessel_BesselkJINI */

#ifndef _Included_edu_oa_curvature_bessel_BesselkJINI
#define _Included_edu_oa_curvature_bessel_BesselkJINI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_oa_curvature_bessel_BesselkJINI
 * Method:    besselk
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_oa_curvature_bessel_BesselkJINI_besselk
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
